import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layouts/MainLayout";
import { getHomeData } from "@/actions/home";
import { getOgImage } from "@/utils";
import { OpenGraphType } from "next/dist/lib/metadata/types/opengraph-types";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  try {
    const data = await getHomeData();
    const defaultTitle = "SPBA - Singapore Pawnbrokers Association";
    const defaultDescription = "The official website of Singapore Pawnbrokers Association";

    return {
      title: data?.title || defaultTitle,
      description: data?.og_description || data?.title || defaultDescription,
      openGraph: {
        title: data?.title || defaultTitle,
        description: data?.og_description || data?.title || defaultDescription,
        url: data?.og_url || "https://www.spba.com.sg",
        images: [
          {
            url: data ? getOgImage(data) : "/og-image.jpg",
            width: 1200,
            height: 630,
            alt: data?.title || defaultTitle,
          },
        ],
        type: (data?.og_type as OpenGraphType) || "website",
      },
    };
  } catch (error) {
    console.error("Error generating metadata:", error);
    return {
      title: "SPBA - Singapore Pawnbrokers Association",
      description: "The official website of Singapore Pawnbrokers Association",
    };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
